### ISSUE TITLE
Delete should not validate non-key attributes

### ISSUE THREAD

**Issue by garrettheel** [pynamodb/PynamoDB#216]
There should be a way to delete items without requiring validation of non-keys.

Currently, if I do `MyModel(some_hash_key=value).delete()` then I'll get an exception like this:

```
  File "/somefile.py", line 1, in delete
    MyModel(some_hash_key=value).delete()
  File "/usr/local/lib/python3.4/site-packages/pynamodb/models.py", line 309, in delete
    args, kwargs = self._get_save_args(attributes=False, null_check=False)
  File "/usr/local/lib/python3.4/site-packages/pynamodb/models.py", line 1035, in _get_save_args
    serialized = self._serialize(null_check=null_check)
  File "/usr/local/lib/python3.4/site-packages/pynamodb/models.py", line 1210, in _serialize
    serialized = attr.serialize(value)
  File "/usr/local/lib/python3.4/site-packages/pynamodb/attributes.py", line 429, in serialize
    for k in values:
TypeError: 'NoneType' object is not iterable
```

This is because I have attributes on the model which are required and pynamo is trying to validate them. This shouldn't be necessary for a delete.

A workaround is `MyModel.get(value).delete()`, which forces a `GetItem` and then a `DeleteItem`, but this is not ideal as it adds a network call and read on my table unnecessarily.

FWIW version is 2.0.3

**Comment by yedpodtrzitko** [comment]
I believe this should be fixed by #194, so you can try to use the `devel` branch directly (until a new release will be published to PyPI).

**Comment by garrettheel** [comment]
@yedpodtrzitko great, looks like that might work! I'll give it a try and report back

**Comment by garrettheel** [comment]
#194 does indeed fix this bug. good call @yedpodtrzitko!

**Comment by yedpodtrzitko** [comment]
I'd keep this issue opened until a new release will be published, so if anyone will stumble upon the same problem they wont open another ticket.

**Comment by brandond** [comment]
#194 does not appear to fix it for batch delete. I am doing a rate limited scan within a batch and using attributes_to_get to only populate the hash and range keys. If I try to call batch.delete on the returned objects, it raises an AttributeError.

**Comment by jpinner-lyft** [comment]
Fixed in https://github.com/pynamodb/pynamodb/pull/283
